### ISSUE TITLE
Phoenix 1.4 support?

### ISSUE THREAD

**Issue by edkelly303** [zanderxyz/veil#19]
This library sounds like exactly what I'm looking for, but I'm having a bit of trouble getting the setup instructions to work with a new Phoenix 1.4 project. I had a few compile-time errors like this:

`== Compilation error in file lib/elm_phx_web/controllers/veil/session_controller.ex == ** (CompileError) lib/elm_phx_web/controllers/veil/session_controller.ex:20: undefined function page_path/2`

and

`== Compilation error in file lib/[project_name]_web/controllers/veil/session_controller.ex == ** (CompileError) lib/[project_name]_web/controllers/veil/session_controller.ex:39: undefined function user_path/2`

Which I think are down to the changes in the routing in 1.4. I managed to fix them by adding the appropriate aliases, but when I boot up `mix phx.server`, the page at localhost:4000 doesn't seem to show the `sign-in link in the top right` mentioned in the readme.

I'm also getting a couple of Dialyzer warnings in `lib/[project_name]_web/templates/veil/user/form.html.eex`: 

`Function 'form.html'/1 has no local return`

and

`The call 'Elixir.Phoenix.HTML.Form':form_for(any(),any(),fun((_) -> {'safe',[any(),...]})) will never return since it differs in the 3rd argument from the success typing arguments: any(),any(),maybe_improper_list())`

Which I guess may be related to this issue, but are beyond me to work out at the moment.

**Comment by zanderxyz** [comment]
Hi,

Sorry for the delay in responding. I had not realised there had been any breaking changes - will try and update this later today.

Thanks for letting me know

**Comment by zanderxyz** [comment]
Now updated - version 0.2.2 works for me with a new Phoenix 1.4 project. Give it a try and let me know if it doesn't work for you.

**Comment by edkelly303** [comment]
Thank you - it works nicely now! Sorry it took me so long to confirm - I moved on to other projects and have only just got back to this.
